language: bash
services:
  - docker
addons:
  apt:
    packages:
      - jq
jobs:
  include:
    - stage: Get latest tag.
      script: export RELEASE_NEW=$(curl -sL https://api.github.com/repos/tdedobbeleer/soccer-ws/tags |jq -r ".[].name" | head -n1)
    - stage: Compare with current release.
      script: ./scripts/getNewRelease.sh
    - stage: Push release to repo.
      if: env(RELEASE) IS present
      script: ./scripts/pushNewRelease.sh
    - stage: Build docker image.
      if: env(RELEASE) IS present
      before_script:
        - mkdir -vp ~/.docker/cli-plugins/
        - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.10.0/buildx-v0.10.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
        - chmod a+x ~/.docker/cli-plugins/docker-buildx
      script:
        - curl https://github.com/tdedobbeleer/soccer-ws/releases/download/$RELEASE/ws-$RELEASE.jar --output soccer-ws.jar
        - echo "${DOCKER_PASSWORD}" | docker login --username $DOCKER_USER --password-stdin
        - docker buildx create --use
        - docker buildx build --build-arg RELEASE=${TRAVIS_TAG} --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag $DOCKER_USER/soccer-ws:latest .
        - docker buildx build --build-arg RELEASE=${TRAVIS_TAG} --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag $DOCKER_USER/soccer-ws:${RELEASE}_${TRAVIS_BUILD_NUMBER} .