language: bash
services:
  - docker
addons:
  apt:
    packages:
      - jq
install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.10.0/buildx-v0.10.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
script: ./scripts/check_new_release.sh
after_success:
  - ./scripts/docker_release.sh