version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_and_release:
          filters:
            branches:
              only:
                - master


jobs:
  "build_and_release":
    working_directory: ~/repo
    docker:
      - image: cimg/base:2023.02
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: install-jq
          command: sudo apt install jq
      - checkout
      - run:
          name: docker-deploy
          command: sh ./scripts/docker_release.sh